### ISSUE TITLE
Invalid format for plugins_dir

### ISSUE THREAD

**Issue by keltanas** [noiselabs/SmartyBundle#40]
If I need to install a plugin directory, then Smarty ceases to see the default directory.
This is because the function [setPluginsDir](http://www.smarty.net/docs/en/api.set.plugins.dir.tpl), through which there is a pass option `plugins_dir`

``` php
class Smarty extends Smarty_Internal_TemplateBase

    public function setPluginsDir($plugins_dir)
    {
        $this->plugins_dir = array();
        foreach ((array) $plugins_dir as $k => $v) {
            $this->plugins_dir[$k] = rtrim($v, '/\\') . DS;
        }

        return $this;
    }
```

erases the specified directory and sets new.

I think it would be good to give the ability to set an array `plugins_dir`

``` php
->arrayNode('plugins_dir')
    ->prototype('scalar')->end()
->end()
```

``` yml
smarty:
    options:
        plugins_dir:
            - %kernel.root_dir%/../vendor/smarty/smarty/distribution/libs/plugins
            - %kernel.root_dir%/Resources/plugins
```
